/** Seed data for normalized city → brgy hierarchy. */
export const CITY_BRGY_SEEDS = [
  {
    city: 'Angeles City',
    barangays: [
      'Agapito del Rosario',
      'Amsic',
      'Anunas',
      'Balibago',
      'Capaya',
      'Claro M. Recto',
      'Cuayan',
      'Cutcut',
      'Lourdes North West',
      'Lourdes Sur East',
      'Lourdes Sur',
      'Malabanias',
      'Margot',
      'Mining',
      'Ninoy Aquino',
      'Pampang',
      'Pandan',
      'Pulungbulu',
      'Pulung Cacutud',
      'Pulung Maragul',
      'Salapungan',
      'San Jose',
      'San Nicolas',
      'Sta. Teresita',
      'Sta. Trinidad',
      'Sto. Cristo',
      'Sto. Domingo',
      'Sto. Rosario',
      'Sapalibutad',
      'Sapa Libutad',
      'Tabun',
      'Virgen Delos Remedios',
    ],
  },
  {
    city: 'Mabalacat',
    barangays: [
      'Atlu-Bola',
      'Bical',
      'Bundagul',
      'Cacutud',
      'Calumpang',
      'Camachiles',
      'Dapdap',
      'Dau',
      'Dolores',
      'Duquit',
      'Lakandula',
      'Mabiga',
      'Macapagal Village',
      'Mamatitang',
      'Mangalit',
      'Poblacion',
      'San Francisco',
      'San Joaquin',
      'San Isidro',
      'San Vicente',
      'Santa Ines',
      'Santa Maria',
      'Santo Rosario',
      'Sapang Biabas',
      'Sapang Balen',
      'Tabun',
      'Tacondo',
      'Xevera',
    ],
  },
  {
    city: 'Clark',
    barangays: [
      'Clark Freeport Zone',
      'Clark Global City',
      'Mimosa',
      'Clark Center',
      'Airport Area',
      'CDC Area',
      'The Sharp Clark Hills',
    ],
  },
  {
    city: 'San Fernando',
    barangays: [
      'Sindalan',
      'Telabastagan',
      'Dolores',
      'Lourdes',
      'Bulaon',
      'Calulut',
      'San Jose',
      'Baliti',
      'Del Pilar',
      'Maimpis',
    ],
  },
  {
    city: 'Magalang',
    barangays: [
      'San Francisco',
      'San Nicolas I',
      'San Nicolas II',
      'Santa Cruz',
      'Dolores',
      'San Isidro',
      'Ayala',
      'San Jose',
      'Turu',
      'Camias',
    ],
  },
  {
    city: 'Porac',
    barangays: [
      'Pio',
      'Manibaug Paralaya',
      'Manibaug Pasig',
      'Manibaug Libutad',
      'Pulung Santol',
      'Sta. Cruz',
      'Dolores',
      'Calzadang Bayu',
      'Salu',
      'Babo Sacan',
    ],
  },
  {
    city: 'Bacolor',
    barangays: [
      'Cabalantian',
      'San Vicente',
      'Cabetican',
      'Cabambangan',
      'Calibutbut',
      'Macabacle',
      'San Antonio',
      'Santa Barbara',
      'Parulog',
      'Potrero',
    ],
  },
];
